[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "herop-geodata"
version = "0.1.0"
dependencies = [
  "geopandas",
  "click",
  "boto3",
  "requests",
  "tqdm",
  "python-dotenv",
  "marko",
]
